-- Primera practica
CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);

-- ACTIVAMOS MODO DE CONSOLA
SET SERVEROUTPUT ON;

--BLOQUE PL SQL
DECLARE
EDAD INTEGER;
YEARS INTEGER;
BEGIN
YEARS:=42;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('tU EDAD EN DIAS ES:'||EDAD);
END;
/
--CREAR UN BLOQUE PL SQL QUE GENERE 200,000 REGISTROS EN SECUENCIA ASCENDIENTES EN LA TABLA DANCE



BEGIN 

  FOR I IN 1..200000 LOOP
    INSERT INTO DANCE VALUES(I, 'LEZAMA',44);
    
    END LOOP;
    
    END;
    /
    --HACEMOS UN SELECT PARA VER QUE DIABLOS HIZO
    
  SELECT * FROM DANCE;
  
  --SISTEMA DE PELICULAS LA DE SALA SERA DE TAREA 
  
  CREATE TABLE PELICULA (ID_PELICULA INTEGER,
                        TITULO VARCHAR2(120),
                        SINOPSIS VARCHAR2(500),
                        CLASIFICACION VARCHAR(5),
                        CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)
                        );
                        DESCRIBE PELICULA;
                        
 CREATE TABLE HORARIO(ID_HORARIO INTEGER,
                      ID_PELICULA INTEGER,
                      HORARIO VARCHAR2(8),
                      CONSTRAINT PK_ID_HORARIO PRIMARY KEY(ID_HORARIO),
                      CONSTRAINT FK1_ID_PELICULA FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
                      );
                      DESCRIBE HORARIO;
