
  
  CREATE TABLE PELICULA (ID_PELICULA INTEGER,
                        TITULO VARCHAR2(120),
                        SINOPSIS VARCHAR2(500),
                        CLASIFICACION VARCHAR(5),
                        CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)
                        );
                        DESCRIBE PELICULA;
                        
 CREATE TABLE HORARIO(ID_HORARIO INTEGER,
                      ID_PELICULA INTEGER,
                      HORARIO VARCHAR2(8),
                      CONSTRAINT PK_ID_HORARIO PRIMARY KEY(ID_HORARIO),
                      CONSTRAINT FK1_ID_PELICULA FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
                      );
                      DESCRIBE HORARIO;
                      
CREATE SEQUENCE sec_pelicula
  start with 1
  increment by 1
  nomaxvalue;
  

--HAY QUE EJECUTARLO ANTES DE LOS PROCEDIMIENTOS
set serveroutput on;
CREATE OR REPLACE PROCEDURE HOLA_MUNDO(NOMBRE IN VARCHAR2)
AS
BEGIN 
--AQUI LA LOGICA

DBMS_OUTPUT.PUT_LINE('HOLA COMO ESTAS'||NOMBRE);
END;
/

BEGIN
HOLA_MUNDO('JORGE EDGAR');
END;
/

DECLARE
VALOR NUMBER;
BEGIN
SUMA(12,8,VALOR);
dbms_output.put_line('LA SUMA ES'||VALOR);
END;
/
--PROCEDIMIENTO GUARDAR PELICULA
CREATE OR REPLACE PROCEDURE GUARDAR_PELICULA 
(MY_ID_PELICULA OUT NUMBER  , MY_TITULO IN VARCHAR2  , MY_SINOPSIS IN VARCHAR2  , MY_CLASIFICACION IN VARCHAR2 )
AS 
BEGIN
  SELECT SEC_PELICULA.NEXTVAL INTO MY_ID_PELICULA FROM DUAL;
  INSERT INTO PELICULA VALUES(MY_ID_PELICULA,MY_TITULO,MY_SINOPSIS,MY_CLASIFICACION);
  
END GUARDAR_PELICULA;


DECLARE
VALOR INTEGER;
BEGIN
GUARDAR_PELICULA(VALOR,'EL RENACIDO','ESTA MAS O MENOS','B15');
END;
/

SELECT * FROM PELICULA;
